####################################
#         L O B B Y  S H O P       #
####################################

#Set your Prefix:
Prefix: "&b[&aTeudaria&b] &e"

#Set how long it takes to use the Grappling Hook a second Time
Grappling Hook Cooldown: 80

#Set how much the things in the Shop costs
Price:
  heart: 0
  totem: 0
  grapplingHook: 0


#Plugin by TeamStrati and NupsNils