####################################
#      L O B B Y  S Y S T E M      #
####################################

#Set your Prefix:
Prefix: "&b[&aTeudaria&b] &e"

#Messages
Discord:
  Message: 'Unser Community Discord: '
  Message2: '>>Klicke hier<<'
  HoverMessage: 'Join gerne'
  Link: 'https://discord.gg/ZK6DFbJTK6'

Website:
  Message: 'Unsere Website: '
  Message2: 'www.teudaria.de'
  HoverMessage: 'Schau doch mal vorbei!'
  Link: 'https://www.teudaria.de'

Rules:
  Message: 'Das sind unsere Regeln: '
  Message2: '>>Klicke hier<<'
  HoverMessage: 'Beachte sie!'
  Link: 'https://teudaria.de/regeln'

Application:
  Message: 'Willst du die Streamer oder YouTuber Rolle oder m\u00f6chtest dich im Team bewerben? '
  Message2: '>>Bewirb dich hier<<'
  HoverMessage: 'Bewirb dich gerne'
  Link: 'https://teudaria.de/forum/'


#Cooldowns:
Grappling Hook Cooldown: 80
Player Hider Cooldown: 20

#Set how much the things in the Shop costs
Price:
  #Cosmetics
  heart: 0
  totem: 0
  EmeraldHalo: 0
  AngryHead: 0
  fire: 0
  soul: 0
  portal: 0

  #Items
  grapplingHook: 0

#Navigator
Navigator Items:
  Slot1:
    enabled: false
    Material: 'AIR'
    Display Name: '&aNothing'
    Warp Name: "no"

  Slot2:
    enabled: false
    Material: 'AIR'
    Display Name: '&aNothing'
    Warp Name: "no"

  Slot3:
    enabled: true
    Material: 'MAGMA_CREAM'
    Display Name: '§6§lSpawn'
    Warp Name: "spawn"

  Slot4:
    enabled: false
    Material: 'AIR'
    Display Name: '&aNothing'
    Warp Name: "no"

  Slot5:
    enabled: true
    Material: 'IRON_AXE'
    Display Name: '§b§lCityBuild'
    Warp Name: "citybuild"

  Slot6:
    enabled: false
    Material: 'AIR'
    Display Name: '&aNothing'
    Warp Name: "no"

  Slot7:
    enabled: true
    Material: 'MUSIC_DISC_MALL'
    Display Name: '§d§lMinigames'
    Warp Name: "minigames"

  Slot8:
    enabled: false
    Material: 'AIR'
    Display Name: '&aNothing'
    Warp Name: "no"

  Slot9:
    enabled: false
    Material: 'AIR'
    Display Name: '&aNothing'
    Warp Name: "no"


#Cookie Clicker Ressource Pack (The Block is a Gold Block)
use-ressource-pack: true

#Permissions
Permissions:
  Trails:
    heart: 'LobbySystem.Trails.heart'
    totem: 'LobbySystem.Trails.totem'
    EmeraldHalo: 'LobbySystem.Trails.EmeraldHalo'
    AngryVillager: 'LobbySystem.Trails.AngryVillager'
    fire: 'LobbySystem.Trails.fire'
    soul: 'LobbySystem.Trails.soul'
    portal: 'LobbySystem.Trail.portal'
  build: 'LobbySystem.build'
  warps: 'LobbySystem.warps'
  map: 'LobbySystem.map'
  setcookie: 'LobbySystem.setcookie'







#########################################
#  Plugin by TeamStrati feat. NupsNils #
########################################