####################################
#      L O B B Y  S Y S T E M      #
####################################

#Set your Prefix:
Prefix: "&b[&aTeudaria&b] &e"

#Set how long it takes to use the Grappling Hook a second Time
Grappling Hook Cooldown: 80

#Set how much the things in the Shop costs
Price:
  #Cosmetics
  heart: 0
  totem: 0
  EmeraldHalo: 0
  AngryHead: 0
  fire: 0

  #Items
  grapplingHook: 0

#Permissions
Permissions:
  Trails:
    heart: 'LobbySystem.Trails.heart'
    totem: 'LobbySystem.Trails.totem'
    EmeraldHalo: 'LobbySystem.Trails.EmeraldHalo'
    AngryVillager: 'LobbySystem.Trails.AngryVillager'
    fire: 'LobbySystem.Trails.fire'
  build: 'LobbySystem.build'
  warps: 'LobbySystem.warps'
  map: 'LobbySystem.map'



####################################
#Plugin by TeamStrati and NupsNils #
####################################