####################################
#      L O B B Y  S Y S T E M      #
####################################

#Set your Prefix:
Prefix: "&b[&aTeudaria&b] &e"

#Messages
Discord:
  Message: 'Unser Community Discord: '
  Message2: '>>Klicke hier<<'
  HoverMessage: 'Join gerne'
  Link: 'https://discord.gg/ZK6DFbJTK6'

Website:
  Message: 'Unsere Website: '
  Message2: 'www.teudaria.de'
  HoverMessage: 'Schau doch mal vorbei!'
  Link: 'https://www.teudaria.de'

Rules:
  Message: 'Das sind unsere Regeln: '
  Message2: '>>Klicke hier<<'
  HoverMessage: 'Beachte sie!'
  Link: 'https://teudaria.de/regeln'

Application:
  Message: 'Willst du die Streamer oder YouTuber Rolle oder m\u00f6chtest dich im Team bewerben? '
  Message2: '>>Bewirb dich hier<<'
  HoverMessage: 'Bewirb dich gerne'
  Link: 'https://teudaria.de/forum/'

#Set how long it takes to use the Grappling Hook a second Time
Grappling Hook Cooldown: 80

#Set how much the things in the Shop costs
Price:
  #Cosmetics
  heart: 0
  totem: 0
  EmeraldHalo: 0
  AngryHead: 0
  fire: 0
  soul: 0

  #Items
  grapplingHook: 0

#Permissions
Permissions:
  Trails:
    heart: 'LobbySystem.Trails.heart'
    totem: 'LobbySystem.Trails.totem'
    EmeraldHalo: 'LobbySystem.Trails.EmeraldHalo'
    AngryVillager: 'LobbySystem.Trails.AngryVillager'
    fire: 'LobbySystem.Trails.fire'
    soul: 'LobbySystem.Trails.soul'
  build: 'LobbySystem.build'
  warps: 'LobbySystem.warps'
  map: 'LobbySystem.map'




####################################
#Plugin by TeamStrati and NupsNils #
####################################