name: LobbySystem
version: '${project.version}'
main: TeamStrati.LobbySystem.Main
api-version: 1.16
authors: [ TeamStrati ]
description: Lobby System mit einfachen Configurationen
website: jan-stratmann.de
depend: [Vault]
softdepend: [HolographicDisplays]


commands:
  spenden:
    description: spende 10 Coins an den Server

  shop:
    description: Lobby Shop

  effects:
    description: Öffnet das Effekte Menu

  warp:
    description: Warp

  build:
    description: Build

  map:
    description: Map

  automessage:
    description: Main command for all AutoMessage commands
    aliases: [ automsg, am ]

  website:
    description: Link to the Website
    aliases: [webseite, link]

  discord:
    description: Link to the Discord
    aliases: [dc]

  regeln:
    description: rules
    aliases: [rules]

  bewerben:
    description: apply
    aliases: [apply]

  setcookieclicker:
    description: setcookieclicker

  parkour:
    description: Parkour
